### ISSUE TITLE
bug: Rendering issue with links and wrapped lines

### ISSUE THREAD

**Issue by EricDriussi** [MeanderingProgrammer/render-markdown.nvim#157] opened 2024-09-08 11:43 UTC
### Neovim version (nvim -v)

0.10.1

### Operating system

Linux

### Terminal emulator / GUI

WezTerm

### Describe the bug

For this markdown

```md
text
[a_link](http://hi.com) some more text
text
some long ass line asldkjasdlas [a_really_long_ass_link](https://something.com).
text
```

Given a relatively small window size, I see it rendered like so:

![image](https://github.com/user-attachments/assets/c98dbe2c-09ec-4e1d-bc16-8dfc04ede2cb)

(please ignore the warnings, those are unrelated)

### Expected behavior

I would expect the lines with the links *not* to wrap, since visually there seems to be enough space.
In understand this is due to the links actually taking up that space:

![image](https://github.com/user-attachments/assets/9d9debb3-9628-436a-871a-482c5161463a)

Still, it seems like an odd behavior.

### Healthcheck output

```
render-markdown: require("render-markdown.health").check()

render-markdown.nvim [version] ~
- OK plugin 6.1.4
- OK neovim >= 0.10

render-markdown.nvim [configuration] ~
- OK valid

render-markdown.nvim [nvim-treesitter] ~
- OK installed
- OK markdown: parser installed
- OK markdown: highlight enabled
- OK markdown_inline: parser installed
- OK markdown_inline: highlight enabled
- WARNING latex: parser not installed
  - ADVICE:
    - Disable LaTeX support to avoid this warning by setting { latex = { enabled = false } }

render-markdown.nvim [executables] ~
- WARNING latex2text: not installed
  - ADVICE:
    - Disable LaTeX support to avoid this warning by setting { latex = { enabled = false } }

render-markdown.nvim [conflicts] ~
- OK headlines: not installed
- OK obsidian: not installed
```

### Plugin configuration

(taken from lazyvim: https://www.lazyvim.org/extras/lang/markdown#render-markdownnvim)
```lua
{
  "MeanderingProgrammer/render-markdown.nvim",
  opts = {
    file_types = { "markdown", "norg", "rmd", "org" },
    code = {
      sign = false,
      width = "block",
      right_pad = 1,
    },
    heading = {
      sign = false,
      icons = {},
    },
  },
  ft = { "markdown", "norg", "rmd", "org" },
  config = function(_, opts)
    require("render-markdown").setup(opts)
    LazyVim.toggle.map("<leader>um", {
      name = "Render Markdown",
      get = function()
        return require("render-markdown.state").enabled
      end,
      set = function(enabled)
        local m = require("render-markdown")
        if enabled then
          m.enable()
        else
          m.disable()
        end
      end,
    })
  end,
}
```

### Plugin error log

N/A

### Confirmations

- [X] I have provided markdown text for any screenshots used in my description & understand that my issue will be closed if I have not

### Additional information

If this is expected behavior, any tips on how to avoid it on my side would be greatly appreciated.
Also, thanks for the great plugin!

**Comment by MeanderingProgrammer** [comment] 2024-09-08 23:09
Duplicate of: https://github.com/MeanderingProgrammer/render-markdown.nvim/issues/82

Unfortunately no workaround

**Closed** 2024-09-08 23:09 UTC
Labels: bug
