### ISSUE TITLE
bug: left_pad does not work with tabs

### ISSUE THREAD

**Issue by FaisalAl-Rayes** [MeanderingProgrammer/render-markdown.nvim#230] opened 2024-11-08 13:40 UTC
### Neovim version (nvim -v)

0.10.1

### Neovim distribution

LazyVim

### Operating system

MacOS

### Terminal emulator / GUI

iTerm2

### Describe the bug

When i set the "code" configuration as shown blow, with a left_pad and a right_pad defined it actually makes the right_pad be (left_pad + declared value of right_pad) 6 in this case.

this is from [the wiki](https://github.com/MeanderingProgrammer/render-markdown.nvim/wiki/CodeBlocks#width-block-padding)

```lua
return {
  "MeanderingProgrammer/markdown.nvim",
  main = "render-markdown",
  name = "render-markdown",
  dependencies = {
    "nvim-treesitter/nvim-treesitter",
    "nvim-tree/nvim-web-devicons"
  },
  config = function ()
    require("render-markdown").setup(
      {
        code = {
          width = "block",
          left_pad = 2,
          right_pad = 4,
        },
      }
    )
  end
}
```
![Screenshot 2024-11-08 at 14 31 36](https://github.com/user-attachments/assets/fa5d3e7a-4623-4fbd-b3e5-c09666d455d2)
```md
if __name__ == "__main__":
	# Usage
	merge_pdfs(sys.argv[1], sys.argv[2], "merged_output.pdf")
\`\`\`
aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
```

My suspicion is that these are happening in these areas of the code:
[area1](https://github.com/MeanderingProgrammer/render-markdown.nvim/blob/bee16b21bf47b64ceda8c9bb281d4b576d329c0f/lua/render-markdown/render/code.lua#L61)
[area2](https://github.com/MeanderingProgrammer/render-markdown.nvim/blob/bee16b21bf47b64ceda8c9bb281d4b576d329c0f/lua/render-markdown/render/heading.lua#L149)

### Expected behavior

The right padding should only be the value of the right_pad value in the config and not the sum of the left_pad and right_pad (value from the config)

### Healthcheck output

```text
render-markdown: require("render-markdown.health").check()

render-markdown.nvim [version] ~
- OK plugin 7.5.1
- OK neovim >= 0.10

render-markdown.nvim [configuration] ~
- OK valid

render-markdown.nvim [nvim-treesitter] ~
- OK installed
- OK markdown: parser installed
- OK markdown: highlight enabled
- OK markdown_inline: parser installed
- OK markdown_inline: highlight enabled
- WARNING latex: parser not installed
  - ADVICE:
    - Disable LaTeX support to avoid this warning by setting { latex = { enabled = false } }

render-markdown.nvim [executables] ~
- OK latex2text: installed

render-markdown.nvim [conflicts] ~
- OK headlines: not installed
- OK obsidian: installed but should not conflict
```

### Plugin configuration

```lua
return {
  "MeanderingProgrammer/markdown.nvim",
  main = "render-markdown",
  name = "render-markdown",
  dependencies = {
    "nvim-treesitter/nvim-treesitter",
    "nvim-tree/nvim-web-devicons"
  },
  config = function ()
    require("render-markdown").setup(
      {
        code = {
          width = "block",
          left_pad = 2,
          right_pad = 4,
        },
      }
    )
  end
}
```

### Plugin error log

```text
N/A
```

### Confirmations

- [X] I have updated this plugin to the latest version using my plugin manager
- [X] I have provided the text contained in all screenshots as raw text in this issue. This means if there is a screenshot below it is the copy pasted contents of the file in the screenshot. I understand that my issue will be closed if I have not.

**Comment by MeanderingProgrammer** [comment] 2024-11-08 20:23
The issue is that the lines in the code block have tabs and the left padding (made up of spaces) is not applied as a result.

Changing the tabs to spaces fixes this. For instance the following code block works correctly with your configuration:

````
```python
if __name__ == "__main__":
    # Usage
    merge_pdfs(sys.argv[1], sys.argv[2], "merged_output.pdf")
```
````

I'll see if I can handle tabs.

**Comment by MeanderingProgrammer** [comment] 2024-11-08 22:19
Fixed here: https://github.com/MeanderingProgrammer/render-markdown.nvim/commit/d80acb3f4ccc88052f65fa0a26e46c106b328bbe

There's no way to shift text to the left by 2 spaces when it's before a tab and your tab size is 4. So now the next multiple of your tab size will be used as the left padding. So your example will be left padded by 4 spaces and the right padding will be whatever value you set, in this case also 4.

This is just how tabs work:

- Text `a\tb` displayed as `a   b`
- But ` a\tb` displayed as ` a  b`

The extra space in the second example doesn't shift the `b` anywhere and the text remains the same width overall. This is the same behavior you were seeing.

**Closed by MeanderingProgrammer** 2024-11-08 22:19 UTC
Labels: bug
