### ISSUE TITLE
bug: links that would normally be too long and wrap cause virtual lines when none needed

### ISSUE THREAD

**Issue by avih7531** [MeanderingProgrammer/render-markdown.nvim#160] opened 2024-09-10 15:20 UTC
### Neovim version (nvim -v)

0.10.1

### Operating system

Arch Linux

### Terminal emulator / GUI

Alacritty

### Describe the bug

Markdown links which normally would be wrapped if not for the render cause the render to make a virtual line. See below:
![image](https://github.com/user-attachments/assets/b9d6e81a-4263-4d09-983d-7dd0be0ce58b)

Turns in to this:
![image](https://github.com/user-attachments/assets/573719b6-15ba-4e9d-bb4b-d57b12c25218)

See this too:
![image](https://github.com/user-attachments/assets/ef1d770d-b8c6-4aeb-aa34-ecde05c961c7)

Test code:
```markdown
# Lecture 3
### Avi Herman
### 9/10/2024

## Table of Contents
- [Recap and Practice of Lecture 2](#recap-and-practice-of-lecture-2)
- [Newtown's Third Law](#newtowns-third-law)
- [Support Forces](#support-forces)
- [Energy and Work](#energy-and-work)
- [Lecture 3 Question Set](#lecture-3-question-set)
  - [Why doesn't Newton’s third law imply that all forces cancel each other out?](#1-why-doesnt-newtons-third-law-imply-that-all-forces-cancel-each-other-out)
  - [How are ramps useful? How do they affect the force required to lift something?](#2-how-are-ramps-useful-how-do-they-affect-the-force-required-to-lift-something)
  - [How many deadlifts of 100 kg could you do with the energy from an average daily food intake?](#3-how-many-deadlifts-of-100-kg-could-you-do-with-the-energy-from-an-average-daily-food-intake)
  - [How much energy is lost from heat radiation in a day?](#4-how-much-energy-is-lost-from-heat-radiation-in-a-day)
  - [How much work is done when pushing a desk with friction?](#5-how-much-work-is-done-when-pushing-a-desk-with-friction)
  - [Where did the energy go in the desk-pushing scenario?](#6-where-did-the-energy-go-in-the-desk-pushing-scenario)
- [PollEV Answers](#pollev-answers)
```

### Expected behavior

If a line doesn't need to be wrapped it won't be wrapped and definitely not cause an empty virtual line 

### Healthcheck output

```
==============================================================================
render-markdown: require("render-markdown.health").check()

render-markdown.nvim [version] ~
- OK plugin 6.3.6
- OK neovim >= 0.10

render-markdown.nvim [configuration] ~
- OK valid

render-markdown.nvim [nvim-treesitter] ~
- OK installed
- OK markdown: parser installed
- OK markdown: highlight enabled
- OK markdown_inline: parser installed
- OK markdown_inline: highlight enabled

render-markdown.nvim [executables] ~
- OK none to check

render-markdown.nvim [conflicts] ~
- OK headlines: not installed
- OK obsidian: not installed
```

### Plugin configuration

```lua
return {
	"MeanderingProgrammer/markdown.nvim",
	ft = { "markdown" },
	dependencies = { "nvim-treesitter/nvim-treesitter", "echasnovski/mini.nvim" },
	config = function()
		require("render-markdown").setup({
			latex = {
				enabled = false,
			},
			quote = { repeat_linebreak = true },
			win_options = {
				showbreak = { default = vim.api.nvim_get_option_value("showbreak", {}), rendered = "  " },
				breakindent = { default = vim.api.nvim_get_option_value("breakindent", {}), rendered = true },
				breakindentopt = { default = vim.api.nvim_get_option_value("breakindentopt", {}), rendered = "" },
				conceallevel = { rendered = 2 },
			},
			code = {
				sign = false,
				width = "block",
			},
		})
	end,
}
```

### Plugin error log

N/A

### Confirmations

- [X] I have provided text for all screenshots & understand that my issue will be closed if I have not

### Additional information

Amazing work thanks so much for everything!

**Comment by MeanderingProgrammer** [comment] 2024-09-10 19:09
Duplicate of: https://github.com/MeanderingProgrammer/render-markdown.nvim/issues/82

Unfortunately no workaround

**Closed by MeanderingProgrammer** 2024-09-10 19:09 UTC
Labels: bug

**Comment by avih7531** [comment] 2024-09-10 20:22
Got it. Thanks anyway!
